name       : zuluCrypt
version    : 5.6.0
release    : 5
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/5.6.0/zuluCrypt-5.6.0.tar.xz : 80eca8681d12a8760aa7f1af455c393b19dcb02c7f58cf8ed555a074db094f1e
license    : GPL-2.0-or-later
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gl)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
    - libgcrypt-devel
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true \
             -DUSE_POLKIT=true
build      : |
    %make
install    : |
    %make_install
