name       : zuluCrypt
version    : 5.3.0
release    : 2
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/5.3.0/zuluCrypt-5.3.0.tar.xz : ae62576a9182f3801f7b9d0f7a6a556ba2b5f5f3ca7a3ca331a47f2c0be883e1
license    : GPL-2.0
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gl)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true
build      : |
    %make
install    : |
    %make_install
