name       : zuluCrypt
version    : 6.2.0
release    : 12
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/6.2.0/zuluCrypt-6.2.0.tar.xz : 090f3d561add1c5a5fc5158bf346155d43e2b42e7c47939a403ae2f8dcf8eaa3
license    : GPL-2.0-or-later
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
    - kwallet-devel
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true \
             -DUSE_POLKIT=true
build      : |
    %make
install    : |
    %make_install
