name       : zuluCrypt
version    : 5.7.0
release    : 6
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/5.7.0/zuluCrypt-5.7.0.tar.xz : d9b07c4bcb5c22fe130e72d0f0f5a92f2b8598c2d0a8551483c1656478869685
license    : GPL-2.0-or-later
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gl)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
    - libgcrypt-devel
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true \
             -DUSE_POLKIT=true
build      : |
    %make
install    : |
    %make_install
