name       : zuluCrypt
version    : 5.5.0
release    : 4
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/5.5.0/zuluCrypt-5.5.0.tar.xz : d1d4ebd2c58e3bc68f53976adefe26632da11425fdd3bf3e1413cf4b6975e52b
license    : GPL-2.0-or-later
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gl)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
    - libgcrypt-devel 
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true \
             -DUSE_POLKIT=true
build      : |
    %make
install    : |
    %make_install
