name       : zuluCrypt
version    : 5.7.1
release    : 8
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/5.7.1/zuluCrypt-5.7.1.tar.xz : c212450876d787cba617cf161dee935742cea7f1dc3d757c6d8e707849dd8806
license    : GPL-2.0-or-later
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
    - kwallet-devel
    - libgcrypt-devel
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true \
             -DUSE_POLKIT=true
build      : |
    %make
install    : |
    %make_install
