name       : zuluCrypt
version    : 5.4.0
release    : 3
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/5.4.0/zuluCrypt-5.4.0.tar.xz : 1752f17183785d8063e5c39945241cef879f46726553e9fbbe1f1d29eccd575c
license    : GPL-2.0
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gl)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true \
             -DUSE_POLKIT=true
build      : |
    %make
install    : |
    %make_install
