name       : zuluCrypt
version    : 6.0.0
release    : 10
source     :
    - https://github.com/mhogomchungu/zuluCrypt/releases/download/6.0.0/zuluCrypt-6.0.0.tar.xz : d149e220e0859f6cd88f45ce3c8de6dc3a632705f9092b86c9aaac490cc442a8
license    : GPL-2.0-or-later
component  : security.crypto
summary    : zuluCrypt is a front end to cryptsetup and tcplay
description: |
    zuluCrypt is a simple, feature rich and powerful solution for hard drives encryption.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(libcryptsetup)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1) # opt
    - pkgconfig(pwquality) # opt
    - pkgconfig(Qt5Core)
    - kwallet-devel
setup      : |
    %cmake . -DCMAKE_INSTALL_LIBDIR=%libdir% \
             -DQT5=true \
             -DUDEVSUPPORT=true \
             -DUSE_POLKIT=true
build      : |
    %make
install    : |
    %make_install
